default_context:
  py: py
  project_name: nb2
  use_src: true
  adapters:
    - builtin:
      - module_name: "nonebot.adapters.onebot.v11"
        project_link: "nonebot-adapter-onebot"
        name: "OneBot V11"
        desc: "OneBot V11 协议"
        author: "yanyongyu"
        homepage: "https://onebot.adapters.nonebot.dev/"
        tags: []
        is_official: true
